# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a2368fec7823c0844f97114dc591d5c3f93e948068721e351646b60de0a198a8d55f67401ac77f8abcde657e1b725bc9f0a94a17c5e0d803bdc2a350afb73b7

test:
  secret_key_base: e8ec6f9639fa090cbb3436a767f694cdc1f9fd09250c9fe2517a57d91682dbf07c99b32d03cade8462b4f038db9ff5abd1139531fc027797410e8f4b64b82aa6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
